/**:
  ros__parameters:
    General.lid_topic: "/livox/lidar"
    General.imu_topic: "/livox/imu"
    General.imu_in_g_unit: true  # Livox IMU outputs in g unit
    General.bagname: "AMvalley03"
    General.previous_map: ""
    General.save_path: "/home/zale/save_datas/save_mars/"
    General.lidar_type: 0
    General.blind: 0.5
    General.point_filter_num: 3
    General.extrinsic_tran: [0.04165, 0.02326, -0.0284]
    General.extrinsic_rota: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
    General.is_save_map: 0

    Odometry.cov_gyr: 0.01
    Odometry.cov_acc: 1.0
    Odometry.rdw_gyr: 0.0001
    Odometry.rdw_acc: 0.0001
    Odometry.down_size: 0.5
    Odometry.dept_err: 0.01
    Odometry.beam_err: 0.01
    Odometry.voxel_size: 4.0
    Odometry.min_eigen_value: 0.01
    Odometry.degrade_bound: 100
    Odometry.point_notime: 0

    LocalBA.win_size: 10
    LocalBA.max_layer: 2
    LocalBA.cov_gyr: 0.01
    LocalBA.cov_acc: 1.0
    LocalBA.rdw_gyr: 0.0001
    LocalBA.rdw_acc: 0.0001
    LocalBA.min_ba_point: 1
    LocalBA.plane_eigen_value_thre: [4.0, 4.0, 4.0, 4.0]
    LocalBA.imu_coef: 0.0001
    LocalBA.thread_num: 5

    Loop.jud_default: 0.40
    Loop.icp_eigval: 9.0
    Loop.ratio_drift: 0.01
    Loop.curr_halt: 10
    Loop.prev_halt: 10
    Loop.acsize: 2
    Loop.mgsize: 2
    Loop.isHighFly: 1

    GBA.voxel_size: 15.0
    GBA.min_eigen_value: 10.0
    GBA.eigen_value_array: [2.0, 2.0, 2.0, 2.0]
    GBA.total_max_iter: 10
