/**:
  ros__parameters:
    General.lid_topic: "/livox/lidar"
    General.imu_topic: "/livox/imu"
    General.imu_in_g_unit: true  # Livox IMU outputs in g unit
    # The file path of the map to be saved
    General.save_path: "/home/zale/save_datas/relc_avia/"
    # The offline map in the save_path to be loaded
    # '#' means the map is not loaded
    General.previous_map: ""
    General.bagname: "compus_elevator"
    General.lidar_type: 0
    General.blind: 0.5
    General.point_filter_num: 3
    General.extrinsic_tran: [0.04165, 0.02326, -0.0284]
    General.extrinsic_rota: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
    # The session is saved in save_path + bagname
    General.is_save_map: 0

    Odometry.cov_gyr: 0.1
    Odometry.cov_acc: 1.0
    Odometry.rdw_gyr: 0.0001
    Odometry.rdw_acc: 0.0001
    # indoor:0.1, outdoor:0.25, high altitude: 0.5
    Odometry.down_size: 0.1
    Odometry.dept_err: 0.02
    Odometry.beam_err: 0.05
    # indoor: 0.5-1, high speed: 2, high altitude: 4
    Odometry.voxel_size: 1.0
    Odometry.min_eigen_value: 0.0025
    # The number of degenrate scans to make the system reset
    Odometry.degrade_bound: 10
    Odometry.point_notime: 0

    LocalBA.win_size: 10
    LocalBA.max_layer: 2
    LocalBA.cov_gyr: 0.01
    LocalBA.cov_acc: 1.0
    LocalBA.rdw_gyr: 0.0001
    LocalBA.rdw_acc: 0.0001
    LocalBA.min_ba_point: 1
    # The plane criterion
    LocalBA.plane_eigen_value_thre: [4.0, 4.0, 4.0, 4.0]
    LocalBA.imu_coef: 0.0001
    LocalBA.thread_num: 5

    Loop.jud_default: 0.5
    Loop.icp_eigval: 10.0
    Loop.ratio_drift: 0.01
    Loop.curr_halt: 10
    Loop.prev_halt: 10
    Loop.acsize: 2
    Loop.mgsize: 2
    Loop.isHighFly: 0

    # GBA use the coarse-to-fine strategy
    # These are the coarse parameters
    GBA.voxel_size: 2.0
    GBA.min_eigen_value: 0.1
    GBA.eigen_value_array: [4.0, 4.0, 4.0, 4.0]
    GBA.total_max_iter: 6
