/**:
  ros__parameters:
    General.lid_topic: "/livox/lidar"
    General.imu_topic: "/livox/imu"
    General.save_path: "/home/zale/save_datas/"
    General.previous_map: ""
    General.bagname: "mid360_init"
    General.lidar_type: 0
    General.blind: 0.5
    General.point_filter_num: 3
    General.extrinsic_tran: [-0.011, -0.02329, 0.04412]
    General.extrinsic_rota: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
    General.is_save_map: 0

    Odometry.cov_gyr: 0.1
    Odometry.cov_acc: 1.0
    Odometry.rdw_gyr: 0.0001
    Odometry.rdw_acc: 0.0001
    Odometry.down_size: 0.1
    Odometry.dept_err: 0.02
    Odometry.beam_err: 0.05
    Odometry.voxel_size: 1.0
    Odometry.min_eigen_value: 0.0025
    Odometry.degrade_bound: 10
    Odometry.point_notime: 0

    LocalBA.win_size: 10
    LocalBA.max_layer: 2
    LocalBA.cov_gyr: 0.01
    LocalBA.cov_acc: 2.0
    LocalBA.rdw_gyr: 0.0001
    LocalBA.rdw_acc: 0.0001
    LocalBA.min_ba_point: 1
    LocalBA.plane_eigen_value_thre: [4.0, 4.0, 4.0, 4.0]
    LocalBA.imu_coef: 0.0002
    LocalBA.thread_num: 5

    Loop.jud_default: 0.45
    Loop.icp_eigval: 9.0
    Loop.ratio_drift: 0.01
    Loop.curr_halt: 10
    Loop.prev_halt: 30
    Loop.acsize: 10
    Loop.mgsize: 5
    Loop.isHighFly: 0

    GBA.voxel_size: 2.0
    GBA.min_eigen_value: 0.01
    GBA.eigen_value_array: [4.0, 4.0, 4.0, 4.0]
    GBA.total_max_iter: 6
