/**:
  ros__parameters:
    General.lid_topic: "/velodyne_points"
    General.imu_topic: "/imu/data"
    General.save_path: "/home/zale/save_datas/urbannav/"
    General.previous_map: ""
    General.bagname: "medium1"
    General.lidar_type: 1
    General.blind: 2.8
    General.point_filter_num: 3
    General.extrinsic_tran: [0.0, 0.0, 0.28]
    General.extrinsic_rota: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
    General.is_save_map: 0

    Odometry.cov_gyr: 0.01
    Odometry.cov_acc: 1.0
    Odometry.rdw_gyr: 0.0001
    Odometry.rdw_acc: 0.0001
    Odometry.down_size: 0.25
    Odometry.beam_err: 0.01
    Odometry.dept_err: 0.01
    Odometry.voxel_size: 2.0
    Odometry.min_eigen_value: 0.01
    Odometry.degrade_bound: 100
    Odometry.point_notime: 0

    LocalBA.win_size: 10
    LocalBA.max_layer: 2
    LocalBA.cov_gyr: 0.01
    LocalBA.cov_acc: 1.0
    LocalBA.rdw_gyr: 0.0001
    LocalBA.rdw_acc: 0.0001
    LocalBA.min_ba_point: 1
    LocalBA.plane_eigen_value_thre: [4.0, 4.0, 4.0, 4.0]
    LocalBA.imu_coef: 0.0001
    LocalBA.thread_num: 5

    Loop.jud_default: 0.45
    Loop.icp_eigval: 15.0
    Loop.ratio_drift: 0.01
    Loop.curr_halt: 10
    Loop.prev_halt: 10
    Loop.acsize: 2
    Loop.mgsize: 2
    Loop.isHighFly: 0

    GBA.voxel_size: 2.0
    GBA.min_eigen_value: 0.01
    GBA.eigen_value_array: [9.0, 9.0, 9.0, 9.0]
    GBA.total_max_iter: 3
